### ISSUE TITLE
Update blockHeight to BigInt

### ISSUE THREAD

**Issue by jamesbayly** [subquery/avalanche-dictionary#2]
Update the following to BigInt

`blockHeight: Int! @index`

Update the hosted service dictionary and reindex from the limit of Int (block 9,999,999)

Check all other dictionaries for this issue

**Comment by stwiname** [comment]
The db column has been changed to bigint. We're waiting on the operation to complete to know the status of data and whether we need to reindex

**Comment by stwiname** [comment]
The operation to change to bigint failed because the data is too large. 

Although not ideal what this is an Int it is not a pressing issue as the postgres Int limit is `2,147,483,647`

**Comment by stwiname** [comment]
The avalanche SDK is being deprecated in favour of the ETH SDK. We will now maintain a dictionary with that, which now resides here https://github.com/subquery/ethereum-subql-dictionaries/blob/main/project-avalanche.yaml
